openapi: 3.0.4
info:
  title: Social Network API
  description: Social network api example
  version: 1.0.0
servers:
  - url: https://social-network.com/api/v1
    description: main server

paths:
  # Опубликовать пост без медиа ленту
  /postOn:
    post:
      summary: Опубликовать пост без медиа файлов 
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserPost'
      responses:
        '201':
          description: Пост без медиа успешно опубликован
          
  # Опубликовать пост с медиа файлами в ленту
  /postOnMedia:
    post:
      summary: Опубликовать пост с медиа файлами
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserMediaPost'
      responses:
        '201':
          description: Пост с медиа успешно опубликован
        '400':
          description: "Неверный формат файла или отсутствует файл"
          
  # Отправить пользователю заявку в друзья
  /friends/invite:
    post:
      summary: Отправить заявку в друзья
      requestBody:
        required: true
        content:
          application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: string
                    format: uuid
                    example: 846df173-3505-4f9c-81aa-2111e477d02b
                  welcomeMessage:
                    type: string
                    maxLength: 128
      responses:
        '201':
          description: Заявка успешно отправлена
          
  # Удалить пользователя из друзей
  /friends/delete{id}:
    delete:
      summary: Удалить пользователя из друзей
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: 846df173-3505-4f9c-81aa-2111e477d02b
      responses:
        '201':
          description: Пользователь успешно удален из друзей


  # Получить данные об анкете пользователя
  /friends/getUserProfile{id}:
    get:
      summary: Получить данные об анкете пользователя
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: 846df173-3505-4f9c-81aa-2111e477d02b
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Пользователь не найден
          
  # Получить данные о друзьях пользователя
  /friends/getUserFriends{id}:
    get:
      summary: Получить данные о друзьях пользователя
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: 846df173-3505-4f9c-81aa-2111e477d02b
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserCommonInfo'
        '404':
          description: Пользователь не найден

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 846df173-3505-4f9c-81aa-2111e477d02b
        userInfo: 
          $ref: '#/components/schemas/UserCommonInfo'
        phone: 
          type: string
          pattern: '^\+?[0-9\s\-\(\)]{7,20}$'  # международный формат
          example: "+79161234567"
        birthDate:
          type: string
          format: date
        friendList:
          type: array
          items: 
            $ref: '#/components/schemas/UserCommonInfo'
      required:
        - id
        - birthDate

    UserCommonInfo:
      type: object
      properties:
        userRef:
          type: string
          format: uuid
          example: 846df173-3505-4f9c-81aa-2111e477d64b
        firstName:
          type: string
          example: Алексей
        secondName:
          type: string
          example: Парамонов
        city:
          type: string
          example: Москва
        age:
          type: integer
          format: int32
          minimum: 0
          maximum: 120
          example: 25
    
    UserMediaPost:
      type: object
      properties:
        file:
          type: string
          format: binary
          description: "Медиафайл (jpg, png, mp4, etc.)"
        caption:
          type: string
          description: "Описание к медиа"
        simplePost:
          $ref: '#/components/schemas/UserPost'
        userId:
            type: string
            format: uuid
            description: "ID пользователя"
            
    UserPost:
      type: object
      properties:
        message:
          type: string
          description: "Текст поста"
        userId:
            type: string
            format: uuid
            description: "ID пользователя"






